packages:
  - playground
onlyBuiltDependencies:
  - better-sqlite3
catalog:
  "@fastify/deepmerge": ^3.1.0
  "@nuxt/devtools": ^2.4.0
  "@nuxt/eslint-config": ^1.3.0
  "@nuxt/kit": ^3.17.0
  "@nuxt/module-builder": ^1.0.1
  "@nuxt/schema": ^3.17.0
  "@nuxt/test-utils": ^3.17.2
  "@tailwindcss/vite": ^4.1.4
  "@types/better-sqlite3": ^7.6.13
  better-auth: ^1.2.7
  better-sqlite3: ^11.9.1
  changelogen: ^0.6.1
  defu: ^6.1.4
  eslint: ^9.25.1
  nuxt: ^3.17.0
  ohash: ^2.0.11
  pathe: ^2.0.3
  scule: ^1.3.0
  tailwindcss: ^4.1.4
  tinyglobby: ^0.2.13
  typescript: ~5.8.3
  vitest: ^3.1.2
  vue-tsc: ^2.2.10
