packages:
  - playground
onlyBuiltDependencies:
  - better-sqlite3
catalog:
  "@fastify/deepmerge": ^3.1.0
  "@nuxt/devtools": ^2.4.1
  "@nuxt/eslint-config": ^1.4.0
  "@nuxt/kit": ^3.17.3
  "@nuxt/module-builder": ^1.0.1
  "@nuxt/schema": ^3.17.3
  "@nuxt/test-utils": ^3.19.0
  "@tailwindcss/vite": ^4.1.7
  "@types/better-sqlite3": ^7.6.13
  better-auth: ^1.2.8
  better-sqlite3: ^11.10.0
  changelogen: ^0.6.1
  defu: ^6.1.4
  eslint: ^9.26.0
  nuxt: ^3.17.3
  ohash: ^2.0.11
  pathe: ^2.0.3
  scule: ^1.3.0
  tailwindcss: ^4.1.7
  tinyglobby: ^0.2.13
  typescript: ~5.8.3
  vitest: ^3.1.3
  vue-tsc: ^2.2.10
